// Code generated by "go run ./cmd/reset". DO NOT EDIT.

package resettest

// Reset сбрасывает Child к начальным значениям.
func (c *Child) Reset() {
	if c == nil {
		return
	}

	c.Value = 0
}

// Reset сбрасывает Container к начальным значениям.
func (c *Container) Reset() {
	if c == nil {
		return
	}

	c.Num = 0
	c.Str = ""
	c.Flag = false
	c.Ratio = 0
	if c.StrPtr != nil {
		(*c.StrPtr) = ""
	}
	if c.NumPtr != nil {
		(*c.NumPtr) = 0
	}
	c.Items = c.Items[:0]
	clear(c.Index)
	c.Child.Reset()
	if c.ChildP != nil {
		(*c.ChildP).Reset()
	}
}
