// Code generated by "go run ./cmd/reset". DO NOT EDIT.

package audit

// Reset сбрасывает Event к начальным значениям.
func (e *Event) Reset() {
	if e == nil {
		return
	}

	e.TS = 0
	e.Metrics = e.Metrics[:0]
	e.IPAddress = ""
}
